version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region $us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - docker build -t $803792208699.dkr.ecr.$us-east-1.amazonaws.com/$kxc-teste:$latest .
      - docker push $803792208699.dkr.ecr.$us-east-1.amazonaws.com/$kxc-teste:$latest
      - echo Deploying the latest version of the application...
      - aws ecs update-service --cluster $kxc-teste-cluster --service $kxc-teste-service --force-new-deployment
artifacts:
  files:
    - '**/*'
  name: kxc-teste
  discard-paths: yes
  type: zip
